# Generated by Django 2.0.3 on 2020-05-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200524_0733'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dinnerplatters',
            options={'verbose_name_plural': 'Dinner Platters'},
        ),
        migrations.AlterModelOptions(
            name='pasta',
            options={'verbose_name_plural': 'Pasta'},
        ),
        migrations.AlterModelOptions(
            name='regularpizza',
            options={'verbose_name_plural': 'Regular Pizza'},
        ),
        migrations.AlterModelOptions(
            name='salad',
            options={'verbose_name_plural': 'Salad'},
        ),
        migrations.AlterModelOptions(
            name='sicilianpizza',
            options={'verbose_name_plural': 'Sicilian Pizza'},
        ),
        migrations.AlterModelOptions(
            name='subs',
            options={'verbose_name_plural': 'Subs'},
        ),
        migrations.AlterModelOptions(
            name='toppings',
            options={'verbose_name_plural': 'Toppings'},
        ),
        migrations.AlterField(
            model_name='dinnerplatters',
            name='large',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='dinnerplatters',
            name='small',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='pasta',
            name='large',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='pasta',
            name='small',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='regularpizza',
            name='large',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='regularpizza',
            name='small',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='salad',
            name='large',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='salad',
            name='small',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='sicilianpizza',
            name='large',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='sicilianpizza',
            name='small',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='subs',
            name='large',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='subs',
            name='small',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
