# Generated by Django 2.0.3 on 2020-05-24 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200524_0742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dinnerplatters',
            old_name='item',
            new_name='items',
        ),
        migrations.RenameField(
            model_name='pasta',
            old_name='item',
            new_name='items',
        ),
        migrations.RenameField(
            model_name='regularpizza',
            old_name='item',
            new_name='items',
        ),
        migrations.RenameField(
            model_name='salad',
            old_name='item',
            new_name='items',
        ),
        migrations.RenameField(
            model_name='sicilianpizza',
            old_name='item',
            new_name='items',
        ),
        migrations.RenameField(
            model_name='subs',
            old_name='item',
            new_name='items',
        ),
    ]
