# Generated by Django 2.0.3 on 2020-05-24 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200524_0745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pasta',
            old_name='large',
            new_name='rate',
        ),
        migrations.RenameField(
            model_name='salad',
            old_name='large',
            new_name='rate',
        ),
        migrations.RemoveField(
            model_name='pasta',
            name='small',
        ),
        migrations.RemoveField(
            model_name='salad',
            name='small',
        ),
    ]
