# Generated by Django 2.0.3 on 2020-05-24 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200524_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasta',
            name='items',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='salad',
            name='items',
            field=models.CharField(max_length=40),
        ),
    ]
