# Generated by Django 2.0.3 on 2020-05-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_registeruser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=64)),
                ('category', models.CharField(max_length=64)),
                ('selection', models.CharField(max_length=64)),
                ('topping', models.CharField(blank=True, max_length=150)),
                ('progress', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': 'Pending Orders',
            },
        ),
        migrations.DeleteModel(
            name='registerUser',
        ),
    ]
